version: "3"
services:
  postgres:
    image: pgvector/pgvector:pg16
    env_file: ./.env
    expose:
      - "5432"
    volumes:
      - ./postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh
      - ./postgres-seed.sql:/postgres-seed.sql

  redis:
    image: redis:7-alpine
    env_file: ./.env
    command: "redis-server --requirepass ${REDIS_PASSWORD} --maxmemory ${REDIS_MAXMEMORY} --maxmemory-policy ${REDIS_MAXMEMORY_POLICY}"
    expose:
      - "6379"

  dns:
    image: nginx:1.25-alpine
    env_file: ./.env
    depends_on:
      - api
      - frontend
    links:
      - api:api
      - frontend:frontend
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./dns.conf:/etc/nginx/nginx.conf

  api:
    build:
      context: ../../backend
      dockerfile: ../infra/ci/api.Dockerfile
    env_file: ./.env
    depends_on:
      - postgres
      - redis
      - worker
      - engine
    links:
      - postgres:postgres
      - redis:redis
      - worker:worker
      - engine:engine
    expose:
      - "1111"

  worker:
    build:
      context: ../../backend
      dockerfile: ../infra/ci/worker.Dockerfile
    env_file: ./.env
    depends_on:
      - postgres
      - redis
    links:
      - postgres:postgres
      - redis:redis
    expose:
      - "1112"

  cli:
    build:
      context: ../../backend
      dockerfile: ../infra/ci/cli.Dockerfile
    env_file: ./.env
    depends_on:
      - postgres
      - redis
    links:
      - postgres:postgres
      - redis:redis

  engine:
    build:
      context: ../../engine
      dockerfile: ../infra/ci/engine.Dockerfile
    env_file: ./.env
    expose:
      - "2222"

  frontend:
    build:
      context: ../../frontend
      dockerfile: ../infra/ci/frontend.Dockerfile
      secrets:
        - env
    env_file: ./.env
    depends_on:
      - api
    links:
      - api:api
    expose:
      - "3333"

secrets:
  env:
    file: ./.env
