#!/bin/bash
set -eo pipefail

psql -U ${POSTGRES_USER} <<-END

-- SUPERUSER is needed to create extensions. Remember to revoke it when not needed!
CREATE USER ${CLANK_DATABASE_USER} WITH
    SUPERUSER
    PASSWORD '${CLANK_DATABASE_PASSWORD}';

CREATE DATABASE ${CLANK_DATABASE_NAME} WITH
    OWNER = ${CLANK_DATABASE_USER};

CREATE DATABASE ${CLANK_DATABASE_NAME}_TEST WITH
    OWNER = ${CLANK_DATABASE_USER};

CREATE USER ${CLANK_DATABASE_READONLY_USER} WITH
    PASSWORD '${CLANK_DATABASE_READONLY_PASSWORD}';

\c ${CLANK_DATABASE_NAME}

GRANT CONNECT ON DATABASE ${CLANK_DATABASE_NAME} TO ${CLANK_DATABASE_READONLY_USER};

GRANT USAGE ON SCHEMA public TO ${CLANK_DATABASE_READONLY_USER};

ALTER DEFAULT PRIVILEGES FOR USER ${CLANK_DATABASE_USER} IN SCHEMA public
GRANT SELECT ON TABLES TO ${CLANK_DATABASE_READONLY_USER};

END

psql -U ${CLANK_DATABASE_USER} -d ${CLANK_DATABASE_NAME} -f postgres-seed.sql
